apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    role: vote
spec:
  selector:
    role: vote
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  externalIPs:
    - 34.66.154.85
    - 35.238.52.10
 
